#!/usr/bin/env bash
# Shim: pvm2sdp inside the SDPB container over CWD (SDPB 2.x converter).
IMG="${QGSE_SDPB_IMAGE:-wlandry/sdpb:2.5.1}"
PLAT=""; [ -n "${QGSE_SDPB_PLATFORM:-}" ] && PLAT="--platform ${QGSE_SDPB_PLATFORM}"
exec docker run --rm $PLAT -v "$PWD:/work" -w /work "$IMG" pvm2sdp "$@"
